// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220102113725_M")]
    partial class M
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationCore.Common.TeamRole", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("ApplicationCore.InvitationProject", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("UserGuid", "ProjectGuid");

                    b.HasIndex("ProjectGuid");

                    b.ToTable("InvitationProject");
                });

            modelBuilder.Entity("ApplicationCore.MemberProject", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectGuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserAccessLevel")
                        .HasColumnType("int");

                    b.HasKey("UserGuid", "ProjectGuid");

                    b.HasIndex("ProjectGuid");

                    b.ToTable("MemberProjects");
                });

            modelBuilder.Entity("ApplicationCore.Project.Project", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPersonalMeetingsPreferred")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsScrumUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ApplicationCore.RequestProject", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("UserGuid", "ProjectGuid");

                    b.HasIndex("ProjectGuid");

                    b.ToTable("RequestProject");
                });

            modelBuilder.Entity("ApplicationCore.RoleProject", b =>
                {
                    b.Property<Guid>("ProjectGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TeamRoleGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjectGuid");

                    b.HasIndex("TeamRoleGuid");

                    b.ToTable("RoleProject");
                });

            modelBuilder.Entity("ApplicationCore.User.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondName")
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApplicationCore.Common.TeamRole", b =>
                {
                    b.HasOne("ApplicationCore.User.User", "User")
                        .WithMany("PreferredRoles")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.InvitationProject", b =>
                {
                    b.HasOne("ApplicationCore.Project.Project", "Project")
                        .WithMany("Invitations")
                        .HasForeignKey("ProjectGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.User.User", "User")
                        .WithMany("Invitations")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.MemberProject", b =>
                {
                    b.HasOne("ApplicationCore.Project.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.User.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.RequestProject", b =>
                {
                    b.HasOne("ApplicationCore.Project.Project", "Project")
                        .WithMany("Requests")
                        .HasForeignKey("ProjectGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.User.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.RoleProject", b =>
                {
                    b.HasOne("ApplicationCore.Project.Project", "Project")
                        .WithMany("RequiredTeamRoles")
                        .HasForeignKey("ProjectGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Common.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleGuid");

                    b.Navigation("Project");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("ApplicationCore.Project.Project", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Requests");

                    b.Navigation("RequiredTeamRoles");
                });

            modelBuilder.Entity("ApplicationCore.User.User", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("PreferredRoles");

                    b.Navigation("Projects");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
